The first password is temporary
ReliefApplications/bms_api pull request #247
Opened 2019-05-13 15:41 UTC by colinethrl

2019-05-27 03:05 UTC, bamoure requested changes

2019-05-27 03:05 UTC, barbaraReliefapps commented on src/UserBundle/Entity/User.php
> +    protected $mustChangePassword;
change to 'changePassword'

2019-05-27 03:05 UTC, barbaraReliefapps commented on src/UserBundle/Entity/User.php
> +    protected $mustChangePassword;
On peut le mettre nullable sinon plutot

2019-05-27 10:39 UTC, colinethrl commented on src/UserBundle/Entity/User.php
> +    protected $mustChangePassword;
Renamed !

2019-05-29 07:03 UTC, bamoure approved these changes

2019-05-29 07:04 UTC, merged