[Stage 2 WIP] Organization branding
ReliefApplications/bms_api pull request #256
Opened 2019-05-20 16:17 UTC by colinethrl

2019-05-29 08:46 UTC, bamoure requested changes

2019-05-29 08:46 UTC, barbaraReliefapps commented on src/CommonBundle/Controller/OrganizationController.php
> +     * @Rest\Get("/organization-print-template", name="print_template")
/organization/print/template

2019-05-29 08:46 UTC, barbaraReliefapps commented on src/CommonBundle/DataFixtures/OrganizationFixtures.php
> +    private $data = [
Pas de fixtures si ?

2019-05-29 08:46 UTC, barbaraReliefapps commented on src/CommonBundle/Controller/OrganizationController.php
> +     * @Rest\Post("/organization/{id}", name="update_organization")
On a besoin d'id ? Faut s'assurer qu'on puisse en avoir une seule

2019-05-29 08:46 UTC, barbaraReliefapps commented on src/CommonBundle/DataFixtures/OrganizationFixtures.php
> +    private $data = [
Ah j'ai compris. Tu mets une fixture comme ça t'as pas de add. Ca me va, mais mets pas d'image dans la fixture (qu'on encombre pas le s3 - et pour voir ce que ça donne sans image)

2019-05-29 14:18 UTC, colinethrl commented on src/CommonBundle/Controller/OrganizationController.php
> +     * @Rest\Get("/organization-print-template", name="print_template")
Je renommerai

2019-05-29 14:19 UTC, colinethrl commented on src/CommonBundle/DataFixtures/OrganizationFixtures.php
> +    private $data = [
J'ai pas encombré le s3 puisque je mets directement un lien vers le s3 ça re upload pas à chaque fois
Et on peut faire sans ? Genre il ont le droit de pas mettre de logo?

2019-05-29 14:19 UTC, colinethrl commented on src/CommonBundle/Controller/OrganizationController.php
> +     * @Rest\Post("/organization/{id}", name="update_organization")
On a pas besoin d'id, mais dans le front on a tout généralisé au niveau des services, avec l'id à chaque fois, et vu que y a pas de route add, a priori y en aura toujours qu'une

2019-05-30 04:00 UTC, barbaraReliefapps commented on src/CommonBundle/DataFixtures/OrganizationFixtures.php
> +    private $data = [
Faudrait que ça soit possible non ?

2019-05-31 07:51 UTC, merged