Dev import format
ReliefApplications/bms_api pull request #260
Opened 2019-05-22 15:16 UTC by colinethrl

2019-05-27 02:58 UTC, bamoure requested changes

2019-05-27 02:58 UTC, barbaraReliefapps commented on src/BeneficiaryBundle/Utils/Mapper/CSVToArrayMapper.php
> +                if (strtolower($value) === $row[$mappingCSV['livelihood']]) {
faut pas faire un strtolower, mais faire un compare case insensitive (strccmp, je crois)

2019-05-27 02:58 UTC, barbaraReliefapps commented on src/BeneficiaryBundle/Utils/Mapper/CSVToArrayMapper.php
> +            if ($livelihood !== null) {
Ca faut le faire dans une fonction à part qui fait le mapping (de manière générale faut cleaner tout le fichier)

2019-05-27 02:58 UTC, barbaraReliefapps commented on src/DistributionBundle/Utils/DistributionCSVService.php
> +                        if (strtolower($value) === $beneficiaryArray[$index]) {
Same

2019-05-27 09:14 UTC, colinethrl commented on src/BeneficiaryBundle/Utils/Mapper/CSVToArrayMapper.php
> +                if (strtolower($value) === $row[$mappingCSV['livelihood']]) {
Changé !

2019-05-27 09:45 UTC, colinethrl commented on src/BeneficiaryBundle/Utils/Mapper/CSVToArrayMapper.php
> +            if ($livelihood !== null) {
Fixer

2019-05-27 09:45 UTC, colinethrl commented on src/DistributionBundle/Utils/DistributionCSVService.php
> +                        if (strtolower($value) === $beneficiaryArray[$index]) {
Fixé

2019-05-29 08:13 UTC, bamoure approved these changes

2019-05-29 08:18 UTC, bamoure approved these changes

2019-05-29 08:20 UTC, merged